/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// This file was automatically generated by TanStack Router.
// It should not be edited manually.

import { createRootRouteWithContext } from '@tanstack/react-router'

// Import Routes
import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create/Register the Root Route
const rootRouteWithContext = rootRoute

// Populate Route Registry
declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and register the route tree
const rootRouteChildren = [IndexImport]

export const routeTree = rootRouteWithContext._addFileChildren(rootRouteChildren) as any
